---
- name: Installing keys/certs from {{ service_account.tls.pki_dir }} (local) to {{ service_account.tls.dest_dir }} (remote)
  ansible.builtin.include_role:
    name: andrewrothstein.tls
  vars:
    tls_become: true
    tls_become_user: root
    tls_src: '{{ service_account.tls.pki_dir }}'
    tls_dest: '{{ service_account.tls.dest_dir }}'
    tls_dest_chown:
      owner: '{{ service_account.user.name }}'
      grp: '{{ service_account.user.group }}'
