---
- name: creating service account group {{ service_account.user.group }}
  become: true
  become_user: root
  group:
    name: '{{ service_account.user.group }}'
    state: present

- name: creating service account user {{ service_account.user.name }}
  become: true
  become_user: root
  user:
    name: '{{ service_account.user.name }}'
    group: '{{ service_account.user.group }}'
    groups: '{{ service_account.user.groups | default([]) }}'
    append: '{{ service_account.user.append | default(false) }}'
    state: present

- name: creating private directories for {{ service_account.user.name }}
  become: true
  become_user: root
  with_items: '{{ service_account.directories | default([]) }}'
  file:
    path: '{{ item.d }}'
    state: directory
    owner: '{{ service_account.user.name }}'
    group: '{{ service_account.user.group }}'
    mode: '{{ item.m | default("0700") }}'

- when: service_account.tls is defined
  include_tasks: pki.yml
