---
- name: Creating service account group {{ service_account_def.user.group }}
  become: true
  become_user: root
  ansible.builtin.group:
    name: '{{ service_account_def.user.group }}'
    state: '{{ service_account_state }}'

- name: Creating service account user {{ service_account_def.user.name }}
  become: true
  become_user: root
  ansible.builtin.user:
    name: '{{ service_account_def.user.name }}'
    group: '{{ service_account_def.user.group }}'
    groups: '{{ service_account_def.user.groups | default([]) }}'
    append: '{{ service_account_def.user.append | default(false) }}'
    state: '{{ service_account_state }}'

- name: Creating private directories for {{ service_account_def.user.name }}
  become: true
  become_user: root
  when: service_account_def.enabled | bool
  with_items: '{{ service_account_def.directories | default([]) }}'
  ansible.builtin.file:
    path: '{{ item.d }}'
    state: directory
    owner: '{{ service_account_def.user.name }}'
    group: '{{ service_account_def.user.group }}'
    mode: '{{ item.m | default("0700") }}'

- name: Installing PKI stuffs
  when:
    - service_account_def.enabled | bool
    - service_account_def.tls is defined
  ansible.builtin.include_tasks: pki.yml
